class TekkenOverlayCommon::BusinessLayer::DefaultFontChanger:
  Enabled: !<!!str> false
  FontSize: 20
class TekkenOverlayCommon::BusinessLayer::FPSUnlocker:
  IsEnabled: !<!!str> true
  FPS: 999
class TekkenOverlayCommon::BusinessLayer::PerformanceStages:
  ShouldCreateSimplifiedStage: !<!!str> false
  ShouldReplaceAllMaterialsWithDefaultMaterial: !<!!str> false
  ShouldDisableAllLights: !<!!str> false
  ShouldDisableClothPhysics: !<!!str> false
  ShouldDisableEffects: !<!!str> false
  ShouldDisableCameraShakes: !<!!str> false
class Tekken8Overlay::BusinessLayer::Interpolation:
  Enabled: !<!!str> true
EngineFlags:
  ViewModeIndex: 3
  PostProcessing: !<!!str> true
  Bloom: !<!!str> true
  LocalExposure: !<!!str> true
  AntiAliasing: !<!!str> true
  TemporalAA: !<!!str> true
  AmbientCubemap: !<!!str> true
  EyeAdaptation: !<!!str> true
  GlobalIllumination: !<!!str> true
  Vignette: !<!!str> true
  AmbientOcclusion: !<!!str> true
  Decals: !<!!str> true
  OnScreenDebug: !<!!str> true
  VisualizeNanite: !<!!str> false
  VisualizeLumen: !<!!str> false
  VisualizeSubstrate: !<!!str> false
  VisualizeGroom: !<!!str> false
  VisualizeVirtualShadowMap: !<!!str> false
  PointLights: !<!!str> true
  SpotLights: !<!!str> true
  RectLights: !<!!str> true
  DepthOfField: !<!!str> true
  MotionBlur: !<!!str> true
  CameraInterpolation: !<!!str> true
  ToneCurve: !<!!str> true
  SeparateTranslucency: !<!!str> true
  ScreenPercentage: !<!!str> true
  ReflectionEnvironment: !<!!str> true
  Specular: !<!!str> true
  ScreenSpaceReflections: !<!!str> true
  LumenReflections: !<!!str> true
  ContactShadows: !<!!str> true
  RayTracedDistanceFieldShadows: !<!!str> true
  CapsuleShadows: !<!!str> true
  VolumetricLightmap: !<!!str> true
  IndirectLightingCache: !<!!str> true
  TexturedLightProfiles: !<!!str> true
  LightFunctions: !<!!str> true
  NaniteMeshes: !<!!str> true
  InstancedStaticMeshes: !<!!str> true
  InstancedFoliage: !<!!str> true
  InstancedGrass: !<!!str> true
  DynamicShadows: !<!!str> true
  Particles: !<!!str> true
  SkeletalMeshes: !<!!str> true
  Translucency: !<!!str> true
  LOD: !<!!str> true
  Lighting: !<!!str> true
  DeferredLighting: !<!!str> true
  StaticMeshes: !<!!str> true
  Landscape: !<!!str> true
  Fog: !<!!str> true
  Game: !<!!str> true
  BSP: !<!!str> true
  LightShafts: !<!!str> true
  Atmosphere: !<!!str> true
  TextRender: !<!!str> true
  Rendering: !<!!str> true
  HMDDistortion: !<!!str> false
  StereoRendering: !<!!str> false
  DistanceCulledPrimitives: !<!!str> false
  SkyLighting: !<!!str> true
  Paper2DSprites: !<!!str> true
  ScreenSpaceAO: !<!!str> true
  DistanceFieldAO: !<!!str> true
  LumenGlobalIllumination: !<!!str> true
  VolumetricFog: !<!!str> true
  WidgetComponents: !<!!str> true
  MediaPlanes: !<!!str> true
  PathTracing: !<!!str> false
  VisualizeCalibrationColor: !<!!str> false
  VisualizeCalibrationGrayscale: !<!!str> false
  VisualizeCalibrationCustom: !<!!str> false
  LumenScreenTraces: !<!!str> true
  LumenDetailTraces: !<!!str> true
  LumenGlobalTraces: !<!!str> true
  LumenFarFieldTraces: !<!!str> true
  LumenSecondaryBounces: !<!!str> true
  LumenShortRangeAmbientOcclusion: !<!!str> true
  ShaderPrint: !<!!str> true
OverlayTotalUsageTime: 38163
FOVChanger:
  IsEnabled: !<!!str> false
  PreserveYFOV: !<!!str> false
  UnlockAspectRatio: !<!!str> false
  WantedFOV: 60
  !<!!str> CameraAspectRatio: -1
class Tekken8Overlay::BusinessLayer::DisplaySettings:
  WantedGlobalIlluminationQuality: 1
  WantedReflectionQuality: 1
  WantedGlobalIlluminationMethod: 0
  WantedReflectionMethod: 2
  WantedAAMethod: 2
  WantedLightColor:
    !<!!str> R: 1
    !<!!str> G: 1
    !<!!str> B: 1
    !<!!str> A: 1
  LastAppliedConfig: ""
  ShouldDisablePostProcessingVolumes: !<!!str> false
  ShouldDisableBakedInLighting: !<!!str> false
  ShouldDisableUpscaling: !<!!str> false
  ShouldDisableCharacterLights: !<!!str> false
  ShouldApplyCustomCharacterLightingColor: !<!!str> false
  ShouldDisableOtherLights: !<!!str> false
  OLEDFix: !<!!str> false
class Tekken8Overlay::BusinessLayer::NetworkLag:
  Enabled: !<!!str> false
  InputLag: 0
class TekkenOverlayCommon::BusinessLayer::AddConsoleMod:
  Enabled: !<!!str> false
LastTimeWindowShown: 1756844318